services:
    mirotalkadmin:
        image: mirotalk/admin:latest
        container_name: mirotalkadmin
        hostname: mirotalkadmin
        ports:
            - '${ADMIN_PORT}:${ADMIN_PORT}'
        volumes:
            - ./frontend:/app/frontend:ro
            - ./backend:/app/backend:ro
            - ./.env:/app/.env:ro
            #- ~/.ssh/id_rsa:/app/id_rsa:ro
        restart: unless-stopped
